# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:51:25+00:00



import argparse
import json
import os
from typing import *

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity
from fastapi import Path

from models import (
    ApiGenClientsGetResponse,
    ApiGenClientsLanguageGetResponse,
    ApiGenServersFrameworkGetResponse,
    ApiGenServersGetResponse,
    GeneratorInput,
    ResponseCode,
)

app = MCPProxy(
    contact={},
    description='This is an online openapi generator server.  You can find out more at https://github.com/OpenAPITools/openapi-generator.',
    license={
        'name': 'Apache 2.0',
        'url': 'https://www.apache.org/licenses/LICENSE-2.0.html',
    },
    title='OpenAPI Generator Online',
    version='6.2.1',
    servers=[{'url': '//api.openapi-generator.tech'}],
)


@app.get('/api/gen/clients', tags=['client_library_creation'])
def client_options():
    """
    Gets languages supported by the client generator
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/gen/clients/{language}', tags=['client_library_creation'])
def get_client_options(language: str):
    """
    Returns options for a client library
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/gen/clients/{language}',
    description=""" Accepts a `GeneratorInput` options map for spec location and generation options """,
    tags=['client_library_creation'],
)
def generate_client(language: str, body: GeneratorInput = ...):
    """
    Generates a client library
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/gen/download/{fileId}',
    description=""" A valid `fileId` is generated by the `/clients/{language}` or `/servers/{language}` POST operations.  The fileId code can be used just once, after which a new `fileId` will need to be requested. """,
    tags=['client_library_creation'],
)
def download_file(file_id: str = Path(..., alias='fileId')):
    """
    Downloads a pre-generated file
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/gen/servers', tags=['server_library_creation'])
def server_options():
    """
    Gets languages supported by the server generator
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/api/gen/servers/{framework}', tags=['server_library_creation'])
def get_server_options(framework: str):
    """
    Returns options for a server framework
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/gen/servers/{framework}',
    description=""" Accepts a `GeneratorInput` options map for spec location and generation options. """,
    tags=['server_library_creation'],
)
def generate_server_for_language(framework: str, body: GeneratorInput = ...):
    """
    Generates a server library
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
