# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:51:25+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, RootModel


class CliOption(BaseModel):
    default: Optional[str] = None
    description: Optional[str] = None
    enum: Optional[Dict[str, str]] = None
    opt: Optional[str] = None
    optValue: Optional[str] = None
    type: Optional[str] = None


class PredicateOfURL(BaseModel):
    pass


class ResponseCode(BaseModel):
    code: Optional[str] = Field(
        None,
        description='File download code',
        examples=['d40029be-eda6-4d62-b1ef-d05e2e91a72a'],
    )
    link: Optional[str] = Field(
        None,
        description='URL for fetching the generated client',
        examples=[
            'http://localhost:8080/api/gen/download/d40029be-eda6-4d62-b1ef-d05e2e91a72a'
        ],
    )


class URLStreamHandler(BaseModel):
    pass


class ApiGenClientsGetResponse(RootModel[List[str]]):
    root: List[str]


class ApiGenClientsLanguageGetResponse(RootModel[Optional[Dict[str, CliOption]]]):
    root: Optional[Dict[str, CliOption]] = None


class ApiGenServersGetResponse(RootModel[List[str]]):
    root: List[str]


class ApiGenServersFrameworkGetResponse(RootModel[Optional[Dict[str, CliOption]]]):
    root: Optional[Dict[str, CliOption]] = None


class AuthorizationValue(BaseModel):
    keyName: Optional[str] = None
    type: Optional[str] = None
    urlMatcher: Optional[PredicateOfURL] = None
    value: Optional[str] = None


class GeneratorInput(BaseModel):
    authorizationValue: Optional[AuthorizationValue] = None
    openAPIUrl: Optional[str] = Field(
        None,
        examples=[
            'https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/modules/openapi-generator/src/test/resources/2_0/petstore.yaml'
        ],
    )
    options: Optional[Dict[str, str]] = None
    spec: Optional[Dict[str, Any]] = None
